admin:
    password: ENC[AES256_GCM,data:mo/PGGiNAseaVveDtbhD2Ow5Pn8=,iv:IJA4phSFcyFLlfcypO4F9w5ZMpUBl5h39007j9IjO8g=,tag:OtCpsIaw95wx7KCx6fUb1g==,type:str]
postgresql:
    auth:
        password: ENC[AES256_GCM,data:YqBZytDrgsyfpzl2QSO0ePpe6o0=,iv:shSuQwnivkjdsfFD0Y8mbzJR9YwKSG0S5TWxFBao6yk=,tag:onUzPx3Sf1trX4snJfZr4w==,type:str]
sops:
    age:
        - recipient: age1lpqp7ue6rj8x020uvlrklk2pz6k6va80qh3c7fzce0v7gq2m3akssrfmkr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmK2Q3UGdzeGo5YVJTOHZi
            Vk5iWDN1YngvTmNNeFBRK0k1RXB5MExPTEZJCnovMVZsOXRjaXBIWk9LMUZxMHhm
            YlZtdElFL2kvdXJLMStkU0NFUk5qNWMKLS0tIDNITWZwcG10MkI5TzhnYlpIcU5s
            YTYwc0pmY0R0aE5pTHIyekpON3Z1ejQKob4junwdnNZO1tK418NCfyQJCSEJpGTB
            NUoG3BiwcHe22pgX9zzWUeLYsfKaqkNFGweIlhU7hhaVYCyvmKfwNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-15T15:27:42Z"
    mac: ENC[AES256_GCM,data:ljLcAtYbTe5oouMDp2f25pSwcbLr7QsZ0TF5DsLPj0tGIibTkpFxIdu+zaEIa6kXt6BdgRco+ULoIuN7tuIs4BSEtMGGQ5Y/ol7gdsvzPEM26BwomaFoR6RvyTaZXDOICTLAiTSMolR4LdMaxvYGMlI8WaOu/cEjH2gOeibx+Sk=,iv:jGjLQWSkX8Jg2pgo+CbFmAa/Bl7lQ//HwlDqRa+WHLM=,tag:JcKudm0tfVq+lqUbojSHFw==,type:str]
    encrypted_regex: .*
    version: 3.11.0
