---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - multus.yaml
  - images.yaml
  - storage.yaml
  - transmission-deployment.yaml
  - transmission-service.yaml
  - radarr.yaml
  - sonarr.yaml
  - bazarr.yaml
  - lidarr.yaml
  - prowlarr.yaml
  - plex-deployment.yaml
  - plex-service.yaml
  - tautulli.yaml
  - mylar3.yaml
  - overseerr.yaml
  - cleanuparr.yaml
  - profilarr.yaml
  - ingress.yaml
